### ISSUE TITLE
[1.1.3][CKAN] Total disaster.

### ISSUE THREAD

**Issue by Erquint** [linuxgurugamer/KWRocketryRedux#12]
Installed using CKAN on KSP 1.1.3 with *graduated power response config*.
* No visual effects during flight(no flame/smoke coming out the nozzles).
* Ridiculous thrust even with thrust limiter set to 0.
* Trying to uninstall crashes CKAN.

**Comment by linuxgurugamer** [comment]
you should take this up with CKAN (the crash issue)

**Comment by linuxgurugamer** [comment]
and I think you installed the 1.2 version into 1.1.3

**Comment by Erquint** [comment]
CKAN wouldn't let me do that unless I force it(which I didn't) or it had been marked as 1.1.3-compatible, which, as I gather it, the responsibility of the dev committing a build to the repository. Anyway using this mod is not critical for me. Just wanted to let you know.
