### ISSUE TITLE
Should this be frozen in NetKAN?

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/KWRocketryRedux#23]
Two different NetKAN files point to this mod, KWRocketryRedux:
```
    "$kref"         : "#/ckan/github/linuxgurugamer/KWRocketryRedux",
```

and KWRocketryRebalanced:

```
    "$kref"         : "#/ckan/spacedock/1497",
```

The downloads are the same. This came up in KSP-CKAN/NetKAN#6138, but now there's a new release that errors out when NetKAN tries to index KWRocketryRedux:

![image](https://user-images.githubusercontent.com/1559108/35006633-fa0d23ac-faee-11e7-8f6e-4a07f3434fa0.png)

... because it doesn't match the netkan data:

```json
    "install" : [
        {
            "find"       : "KWRocketry/GameData/KWRocketry",
```

![image](https://user-images.githubusercontent.com/1559108/35006797-730e8e26-faef-11e7-804b-2c090569570f.png)

Rather than just fixing the install stanza to match the zip, should we take this opportunity to retire Redux, since Rebalanced seems to be the way of the future?

(Tagging @linuxgurugamer to make sure the GitHub notification goes off.)

**Comment by linuxgurugamer** [comment]
Sure, that's fine.  If I get any complaints, I can always fix the redux at that time

**Comment by HebaruSan** [comment]
Thanks! Done in KSP-CKAN/NetKAN#6181.

**Comment by 7ranceaddic7** [comment]
How will users be notified of this change?

Currently, I target redux because of the graduated engine configs.

**Comment by HebaruSan** [comment]
The change already happened. The KWRocketryRedux package hasn't been updated since the 3.1.4 update in June 2017. Since then it's been all KWRocketryRebalanced. On the other hand, the existing versions are not going away. You can still install Redux 3.1.4 or earlier now, and in the future.

All we did today is remove Redux from the list of packages that are checked for new versions.

**Comment by linuxgurugamer** [comment]
@7ranceaddic7 the graduated engine configs are still there in the Rebalanced version.  The only thing that changed was the masses and volumes of the tanks, hence the "Rebalanced"
Also, the old Redux will NOT be updated moving forward.  I suggest you take another look at the Rebalanced, it fixes some issues with the old Redux

**Comment by 7ranceaddic7** [comment]
Thanks for the update.  I will move to the Rebalanced.
