### ISSUE TITLE
Parts won't show up

### ISSUE THREAD

**Issue by dirtymike223** [linuxgurugamer/KWRocketryRedux#24]
I tried installing the mod and followed the instructions included, but the parts do not show up when I launch the game.

I dragged the Game Data folder into the Game Data folder in KSP, and this did not work. I then tried to the Game Data folder in the Squad folder inside KSP's Game Data folder, but that did not work.

I don't know if I did something wrong or if there is another step required. I am using the 1.3.1 one version of kerbal

**Comment by dirtymike223** [comment]
Never mind I figured it out

**Comment by linuxgurugamer** [comment]
So what was the problem?

**Comment by dirtymike223** [comment]
I moved the entire game data folder into the KSP game data folder. I fixed
this by moving the folder inside the game data folder instead.
