### ISSUE TITLE
Typos in 3.75m subassemblies

### ISSUE THREAD

**Issue by jh4c** [linuxgurugamer/KWRocketryRedux#25]
Four of the 3.75m subassemblies, two from the Stock Extras and two from the FAR extras, have typos in the parts which prevent them from loading; this is presumably from an earlier iteration when the part itself had a typo which has since been fixed.

Searching for WildcarXR and replacing it with WildcatXR fixes the issue; no problems with part alignment as far as I can tell.

**Comment by linuxgurugamer** [comment]
Was fixed sometime in the past
