### ISSUE TITLE
Error related to "ModuleAnimateEmissive" in Log file when starting the game with KWRocketry

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/KWRocketryRedux#3]
**Excerpt form the log file:**

[ERR 18:46:47.024] AssemblyLoader: Exception loading 'ModuleAnimateEmissive': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

**And later on:**

[LOG 18:47:06.453] [ModuleManager] Post run call threw an exception in loading ModuleAnimateEmissive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at ModuleManager.MMPatchLoader+<ProcessPatch>d__45.MoveNext () [0x00000] in <filename unknown>:0 

[ERR 18:47:07.408] MechJeb moduleRegistry creation threw an exception in LoadComputerModules loading ModuleAnimateEmissive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at MuMech.MechJebCore.LoadComputerModules () [0x00000] in <filename unknown>:0 

**and finally during part loading:**

[LOG 18:47:11.150] PartLoader: Compiling Part 'KWRocketry/Parts/Aero/150mSRBTop/part/KW2mSRBNoseCone'
[LOG 18:47:11.171] PartLoader: Compiling Part 'KWRocketry/Parts/Aero/KW5mNoseCone/part5m/KW5mNoseCone'
[LOG 18:47:11.183] PartLoader: Compiling Part 'KWRocketry/Parts/Aero/KWFin/part/KWFin'
[LOG 18:47:11.199] PartLoader: Compiling Part 'KWRocketry/Parts/Aero/KWFinGC/part/KWFinGC'
[LOG 18:47:11.214] PartLoader: Compiling Part 'KWRocketry/Parts/Aero/KWNoseCone/part1m/KW1mNoseCone'
[LOG 18:47:11.226] PartLoader: Compiling Part 'KWRocketry/Parts/Aero/KWNoseCone/part2m/KW2mNoseCone'
[LOG 18:47:11.243] PartLoader: Compiling Part 'KWRocketry/Parts/Aero/KWNoseCone/part3m/KW3mNoseCone'
[LOG 18:47:11.255] PartLoader: Compiling Part 'KWRocketry/Parts/Control/KWRadialSAS/part2m/KWSASmodule2mHalf'
[LOG 18:47:11.274] PartLoader: Compiling Part 'KWRocketry/Parts/Control/KWRadialSAS/part3m/KWSASmodule3mHalf'
[LOG 18:47:11.293] PartLoader: Compiling Part 'KWRocketry/Parts/Control/KWRadialSAS/part5m/KWSASmodule5mHalf'
[LOG 18:47:11.313] PartLoader: Compiling Part 'KWRocketry/Parts/Electrical/LargeRadialBatteries/partL/KWRadBattLargeL'
[LOG 18:47:11.326] PartLoader: Compiling Part 'KWRocketry/Parts/Electrical/LargeRadialBatteries/partS/KWRadBattLargeS'
[LOG 18:47:11.339] PartLoader: Compiling Part 'KWRocketry/Parts/Electrical/SmallRadialBatteries/partL/KWRadBattSmallL'
[LOG 18:47:11.351] PartLoader: Compiling Part 'KWRocketry/Parts/Electrical/SmallRadialBatteries/partS/KWRadBattSmallS'
[LOG 18:47:11.363] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/1mMaverick1D/part/KW1mengineMaverick1D'
[ERR 18:47:11.370] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[ERR 18:47:11.378] FloatCurve: Invalid line. Requires two values, 'time' and 'value'

[LOG 18:47:11.392] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/1mVestaVR1/part/KW1mengineVestaVR1'
[ERR 18:47:11.399] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:11.420] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/1mWildcat5/part/KW1mengineWildCatV'
[ERR 18:47:11.427] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[ERR 18:47:11.435] FloatCurve: Invalid line. Requires two values, 'time' and 'value'

[LOG 18:47:11.449] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/2mGriffonG8D/part/KW2mengineGriffonG8D'
[ERR 18:47:11.456] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[ERR 18:47:11.464] FloatCurve: Invalid line. Requires two values, 'time' and 'value'

[LOG 18:47:11.525] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/2mMaverickV/part/KW2mengineMaverickV'
[ERR 18:47:11.532] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:11.554] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/2mSPS/part/KW2mengineSPS'
[ERR 18:47:11.561] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:11.583] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/2mVestaVR9D/part/KW2mengineVestaVR9D'
[ERR 18:47:11.589] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:11.613] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/3mGriffonXX/part/KW3mengineGriffonXX'
[ERR 18:47:11.620] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[ERR 18:47:11.628] FloatCurve: Invalid line. Requires two values, 'time' and 'value'

[LOG 18:47:11.642] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/3mTitanI/part/KW3mengineTitanT1'
[ERR 18:47:11.649] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:11.672] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/3mWildcatXR/part/KW3mengineWildcarXR'
[ERR 18:47:11.678] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:11.701] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/5mEngines/GC/KW5mengineGriffonC'
[ERR 18:47:11.707] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[ERR 18:47:11.715] FloatCurve: Invalid line. Requires two values, 'time' and 'value'

[LOG 18:47:11.728] PartLoader: Compiling Part 'KWRocketry/Parts/Engines/5mEngines/TV/KW5mengineTitanV'
[ERR 18:47:11.734] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:11.757] PartLoader: Compiling Part 'KWRocketry/Parts/FairingBases/KWExpandedFairingBase/Part1mPFE/KW1mFairingPFE'
[ERR 18:47:11.765] Cannot find fx group of that name for decoupler

[ERR 18:47:11.775] Cannot find fx group of that name for decoupler

[LOG 18:47:11.781] PartLoader: Compiling Part 'KWRocketry/Parts/FairingBases/KWExpandedFairingBase/Part2mPFE/KW2mFairingPFE'
[ERR 18:47:11.786] Cannot find fx group of that name for decoupler

[ERR 18:47:11.795] Cannot find fx group of that name for decoupler

[LOG 18:47:11.800] PartLoader: Compiling Part 'KWRocketry/Parts/FairingBases/KWExpandedFairingBase/Part3mPFE/KW3mFairingPFE'
[ERR 18:47:11.806] Cannot find fx group of that name for decoupler

[ERR 18:47:11.815] Cannot find fx group of that name for decoupler

[LOG 18:47:11.820] PartLoader: Compiling Part 'KWRocketry/Parts/FairingBases/KWFairingBase/Part1mPF/KW1mFairingPF'
[ERR 18:47:11.825] Cannot find fx group of that name for decoupler

[ERR 18:47:11.834] Cannot find fx group of that name for decoupler

[LOG 18:47:11.839] PartLoader: Compiling Part 'KWRocketry/Parts/FairingBases/KWFairingBase/Part2mPF/KW2mFairingPF'
[ERR 18:47:11.844] Cannot find fx group of that name for decoupler

[ERR 18:47:11.852] Cannot find fx group of that name for decoupler

[LOG 18:47:11.857] PartLoader: Compiling Part 'KWRocketry/Parts/FairingBases/KWFairingBase/Part3mPF/KW3mFairingPF'
[ERR 18:47:11.863] Cannot find fx group of that name for decoupler

[ERR 18:47:11.871] Cannot find fx group of that name for decoupler

[LOG 18:47:11.876] PartLoader: Compiling Part 'KWRocketry/Parts/Fairings/UnifiedFairings/part1mDecouplerShroud/KW1mDecouplerShroud'
[LOG 18:47:11.924] PartLoader: Compiling Part 'KWRocketry/Parts/Fairings/UnifiedFairings/part2mDecouplerShroud/KW2mDecouplerShroud'
[LOG 18:47:11.940] PartLoader: Compiling Part 'KWRocketry/Parts/Fairings/UnifiedFairings/part3mDecouplerShroud/KW3mDecouplerShroud'
[LOG 18:47:11.956] PartLoader: Compiling Part 'KWRocketry/Parts/Fairings/UnifiedFairings/part5mDecouplerShroud/KW5mDecouplerShroud'
[LOG 18:47:11.972] PartLoader: Compiling Part 'KWRocketry/Parts/Fairings/UnifiedFairings/part5x3_AdaptorShroud/KW5x3AdapterShroud'
[LOG 18:47:12.033] PartLoader: Compiling Part 'KWRocketry/Parts/Fairings/UnifiedFairings5m/Part5mPF/KW5mFairingPF'
[ERR 18:47:12.038] Cannot find fx group of that name for decoupler

[ERR 18:47:12.047] Cannot find fx group of that name for decoupler

[LOG 18:47:12.051] PartLoader: Compiling Part 'KWRocketry/Parts/Fairings/UnifiedFairings5m/Part5mPFE/KW5mFairingPFE'
[ERR 18:47:12.057] Cannot find fx group of that name for decoupler

[ERR 18:47:12.065] Cannot find fx group of that name for decoupler

[LOG 18:47:12.073] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KWSidetank/2mpart/KW2Sidetank'
[LOG 18:47:12.087] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KWSidetank/3mpart/KW3Sidetank'
[LOG 18:47:12.101] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/1mL05/KW1mtankL0_5'
[LOG 18:47:12.115] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/1mL05RCS/KW1mRCSfuel'
[LOG 18:47:12.130] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/1mL1/KW1mtankL1'
[LOG 18:47:12.144] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/1mL2/KW1mtankL2'
[LOG 18:47:12.158] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/1mL4/KW1mtankL4'
[LOG 18:47:12.175] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/1mPancakeL05/KW1mtankPancake'
[LOG 18:47:12.189] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/2mL05/KW2mtankL0_5'
[LOG 18:47:12.203] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/2mL05RCS/KW2mRCSfuel'
[LOG 18:47:12.217] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/2mL1/KW2mtankL1'
[LOG 18:47:12.231] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/2mL2/KW2mtankL2'
[LOG 18:47:12.246] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/2mL4/KW2mtankL4'
[LOG 18:47:12.261] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/2mL4A/KW2mtankL4A'
[LOG 18:47:12.276] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/2mPancakeL05/KW2mtankPancake'
[LOG 18:47:12.291] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/3mL05/KW3mtankL0_5'
[LOG 18:47:12.306] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/3mL05RCS/KW3mRCSfuel'
[LOG 18:47:12.320] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/3mL1/KW3mtankL1'
[LOG 18:47:12.335] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/3mL2/KW3mtankL2'
[LOG 18:47:12.349] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/3mL4/KW3mtankL4'
[LOG 18:47:12.365] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/3mL4A/KW3mtankL4A'
[LOG 18:47:12.380] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/3mPancakeL05/KW3mtankPancake'
[LOG 18:47:12.395] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/5mL0_5/KW5mtankL05'
[LOG 18:47:12.409] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/5mL1_5/KW5mtankL1_5'
[LOG 18:47:12.424] PartLoader: Compiling Part 'KWRocketry/Parts/Fuel/KW_Universal_Tanks/5mL3_5/KW5mtankL3_5'
[LOG 18:47:12.486] PartLoader: Compiling Part 'KWRocketry/Parts/RCS/KWrcsPod/part/KWrcsPod'
[LOG 18:47:12.503] PartLoader: Compiling Part 'KWRocketry/Parts/RCS/KWrcsQuad/part/KWrcsQuad'
[LOG 18:47:12.520] PartLoader: Compiling Part 'KWRocketry/Parts/RCS/KWrcsQuad45/part/KWrcsQuad45'
[LOG 18:47:12.537] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/025mGlobeI/part/KWsrbGlobeI'
[ERR 18:47:12.544] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:12.563] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/075mAeroSRBs/partL/KWsrbGlobeVI'
[ERR 18:47:12.570] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:12.589] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/075mAeroSRBs/partS/KWsrbGlobeV'
[ERR 18:47:12.596] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:12.622] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/150mSRBs/partL/KWsrbGlobeX2'
[ERR 18:47:12.629] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:12.649] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/150mSRBs/partS/KWsrbGlobeX'
[ERR 18:47:12.655] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:12.676] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/250mInlineThor/partL/KWsrbGlobeX10L'
[ERR 18:47:12.683] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:12.703] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/250mInlineThor/partS/KWsrbGlobeX10S'
[ERR 18:47:12.710] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:12.731] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/250mSRBThor/part/KWsrbGlobeX5'
[ERR 18:47:12.737] Cannot find a PartModule of typename 'ModuleAnimateEmissive'

[LOG 18:47:12.757] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/SRBUllage/Large/KWsrbUllageLarge'
[LOG 18:47:12.781] PartLoader: Compiling Part 'KWRocketry/Parts/Solids/SRBUllage/part/KWsrbUllage'
[LOG 18:47:12.806] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KW3mDockingRing/part/KW3mDockingRing'
[LOG 18:47:12.825] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWadapter2x1/21Structural/KWadapter2x1'
[LOG 18:47:12.841] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWadapter3x2/32Structural/KWadapter3x2'
[LOG 18:47:12.857] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWDecoupler/5mDecoupler/KW5mStageDecoupler'
[LOG 18:47:12.872] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWDecoupler/part1m/KW1mDecoupler'
[LOG 18:47:12.888] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWDecoupler/part2m/KW2mDecoupler'
[LOG 18:47:12.904] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWDecoupler/part3m/KW3mDecoupler'
[LOG 18:47:12.966] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFlatadapter2x1/part/KWFlatadapter2x1'
[LOG 18:47:12.980] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFlatadapter3x1/part/KWFlatadapter3x1'
[LOG 18:47:12.998] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFlatadapter3x2/part/KWFlatadapter3x2'
[LOG 18:47:13.010] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFuelAdapter/21part/KWFuelAdapter2x1'
[LOG 18:47:13.024] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFuelAdapter/21part45/KWFuelAdapter2x1S'
[LOG 18:47:13.039] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFuelAdapter/31part/KWFuelAdapter3x1'
[LOG 18:47:13.054] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFuelAdapter/31part45/KWFuelAdapter3x1S'
[LOG 18:47:13.068] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFuelAdapter/32part/KWFuelAdapter3x2'
[LOG 18:47:13.082] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFuelAdapter/32part45/KWFuelAdapter3x2S'
[LOG 18:47:13.097] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFuelAdapter/52part/KWFuelAdapter5x2'
[LOG 18:47:13.111] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWFuelAdapter/53part/KWFuelAdapter5x3'
[LOG 18:47:13.126] PartLoader: Compiling Part 'KWRocketry/Parts/Structural/KWPetalAdapter3m/PetalAdapter3m/KW3mPetalAdapter'
[ERR 18:47:13.131] Cannot find fx group of that name for decoupler

[ERR 18:47:13.132] Cannot find fx group of that name for decoupler

[ERR 18:47:13.140] Cannot find fx group of that name for decoupler

[ERR 18:47:13.141] Cannot find fx group of that name for decoupler

**Comment by linuxgurugamer** [comment]
Do you have the latest ModuleManager installed?

**Comment by linuxgurugamer** [comment]
This is because you aren't running moduleManager.  install it and the problems will go away
