### ISSUE TITLE
Boosters not fixing

### ISSUE THREAD

**Issue by ygorma** [linuxgurugamer/KWRocketryRedux#30]
### **ISSUE DESCRIPTION**
Boosters not fixing on the ship structure. Struts did not solve the issue. Tested with default boosters also, with and without decouplers. A video with the symptom is right below. This happens since release 3.2.7 at least.

Also posted at  KSP forum.
https://forum.kerbalspaceprogram.com/index.php?/topic/193668-ksp-191-bug-boosters-not-fixing/

### **ISSUE TYPE**
 - Bug Report   (Something is broken)

### **KSP and KWRocketryRedux**
KSP: 1.9.1
KWRocketryRedux: 3.2.7.1

### **OS / ENVIRONMENT**
Windows 10 x64

### **STEPS TO REPRODUCE**
https://youtu.be/l1nOAlNp9_U

### **Log Files**
N/A

**Comment by zkx741481546** [comment]
same problem here. KSP1.8.1 KWRocket 3.2.7.1
I guess some mod conflicts with it, but I don't know which is it.

**Comment by zkx741481546** [comment]
I have deleted all my mods only leave KW and ModuleManager4.1.4.dll in the GameDate folder, but this problem still exist! Please fix it asap

**Comment by linuxgurugamer** [comment]
You left the thread hanging, the last line of your last comment was:

"Thanks for your kick answers and support. I'will return ASAP with the result."

and you never returned.  I'll reply on the forum so you can easily find it.

**Comment by linuxgurugamer** [comment]
> same problem here. KSP1.8.1 KWRocket 3.2.7.1
> I guess some mod conflicts with it, but I don't know which is it.

Post your log file in the thread:  https://forum.kerbalspaceprogram.com/index.php?/topic/164554-19x-kw-rocketry-rebalanced/

**Comment by ygorma** [comment]
Problem remains.

```
[LOG 15:16:13.310] Flight State Captured
[LOG 15:16:13.310] Saving Achievements Tree...
[LOG 15:16:13.311] [MessageSystem] Save Messages
[LOG 15:16:13.328] Game State Saved as persistent
[LOG 15:16:14.063] Unpacking Nave sem título
[LOG 15:16:14.094] [UIMasterController]: ShowUI
[LOG 15:16:15.795] KWsrbGlobeX10L Exploded!! - blast awesomeness: 0.5
[LOG 15:16:15.953] KWsrbGlobeX10L Exploded!! - blast awesomeness: 0.5
[LOG 15:16:15.986] KW5mNoseCone Exploded!! - blast awesomeness: 0.5
[LOG 15:16:16.008] KW5mtankL3.5 Exploded!! - blast awesomeness: 0.5
[LOG 15:16:16.180] strutConnectorHeavy Exploded!! - blast awesomeness: 0
[LOG 15:16:17.525] strutConnectorHeavy Exploded!! - blast awesomeness: 0
[LOG 15:16:17.763] [F: 22057]: [strutConnectorHeavy] Collision Enhancer Punch Through - vel: 13.88775

```
[KSP.log](https://github.com/linuxgurugamer/KWRocketryRedux/files/6266784/KSP.log)

**Comment by linuxgurugamer** [comment]
Post in the forum thread.  There is nothing wrong with the mod, by posting in the thread other people can help solve your problem

**Comment by linuxgurugamer** [comment]
I also prefer the Player.log
