### ISSUE TITLE
Missing download link for CKAN version

### ISSUE THREAD

**Issue by jungletek** [linuxgurugamer/KWRocketryRedux#9]
CKAN throws:

Failed to download "https://github.com/linuxgurugamer/KWRocketryRedux/releases/download/3.0.22/KWRocketryRedux-3.0.22.zip" - error: The request was aborted: The connection was closed unexpectedly.

Presumably because the file doesn't exist. Apologies for the unnecessary report if this is intentional, or a delay in an automated release system. I just assumed it's missing due to the way past releases had both 'versions' available to download.

Thanks.

**Comment by jungletek** [comment]
Tried again, and CKAN is pulling the 'Manual' version now, which causes it to crap itself and crash.

Progress? :D

**Comment by linuxgurugamer** [comment]
It was my problem, fixed for now

**Comment by jungletek** [comment]
Nice. Thanks dude, have a good one.
